"""Static seed metadata for 50 top crypto assets (mock mode)."""

SEED_ASSETS = [
    {"symbol": "BTC", "name": "Bitcoin", "slug": "bitcoin", "rank": 1, "cmc_id": 1},
    {"symbol": "ETH", "name": "Ethereum", "slug": "ethereum", "rank": 2, "cmc_id": 1027},
    {"symbol": "USDT", "name": "Tether", "slug": "tether", "rank": 3, "cmc_id": 825},
    {"symbol": "XRP", "name": "XRP", "slug": "xrp", "rank": 4, "cmc_id": 52},
    {"symbol": "BNB", "name": "BNB", "slug": "bnb", "rank": 5, "cmc_id": 1839},
    {"symbol": "SOL", "name": "Solana", "slug": "solana", "rank": 6, "cmc_id": 5426},
    {"symbol": "USDC", "name": "USD Coin", "slug": "usd-coin", "rank": 7, "cmc_id": 3408},
    {"symbol": "DOGE", "name": "Dogecoin", "slug": "dogecoin", "rank": 8, "cmc_id": 74},
    {"symbol": "ADA", "name": "Cardano", "slug": "cardano", "rank": 9, "cmc_id": 2010},
    {"symbol": "TRX", "name": "TRON", "slug": "tron", "rank": 10, "cmc_id": 1958},
    {"symbol": "LINK", "name": "Chainlink", "slug": "chainlink", "rank": 11, "cmc_id": 1975},
    {"symbol": "AVAX", "name": "Avalanche", "slug": "avalanche", "rank": 12, "cmc_id": 5805},
    {"symbol": "XLM", "name": "Stellar", "slug": "stellar", "rank": 13, "cmc_id": 512},
    {"symbol": "TON", "name": "Toncoin", "slug": "toncoin", "rank": 14, "cmc_id": 11419},
    {"symbol": "SHIB", "name": "Shiba Inu", "slug": "shiba-inu", "rank": 15, "cmc_id": 5994},
    {"symbol": "DOT", "name": "Polkadot", "slug": "polkadot", "rank": 16, "cmc_id": 6636},
    {"symbol": "BCH", "name": "Bitcoin Cash", "slug": "bitcoin-cash", "rank": 17, "cmc_id": 1831},
    {"symbol": "LTC", "name": "Litecoin", "slug": "litecoin", "rank": 18, "cmc_id": 2},
    {"symbol": "UNI", "name": "Uniswap", "slug": "uniswap", "rank": 19, "cmc_id": 7083},
    {"symbol": "NEAR", "name": "NEAR Protocol", "slug": "near-protocol", "rank": 20, "cmc_id": 6535},
    {"symbol": "APT", "name": "Aptos", "slug": "aptos", "rank": 21, "cmc_id": 21794},
    {"symbol": "ICP", "name": "Internet Computer", "slug": "internet-computer", "rank": 22, "cmc_id": 8916},
    {"symbol": "ETC", "name": "Ethereum Classic", "slug": "ethereum-classic", "rank": 23, "cmc_id": 1321},
    {"symbol": "FIL", "name": "Filecoin", "slug": "filecoin", "rank": 24, "cmc_id": 2280},
    {"symbol": "ARB", "name": "Arbitrum", "slug": "arbitrum", "rank": 25, "cmc_id": 11841},
    {"symbol": "OP", "name": "Optimism", "slug": "optimism", "rank": 26, "cmc_id": 11840},
    {"symbol": "INJ", "name": "Injective", "slug": "injective", "rank": 27, "cmc_id": 7226},
    {"symbol": "ATOM", "name": "Cosmos", "slug": "cosmos", "rank": 28, "cmc_id": 3794},
    {"symbol": "SUI", "name": "Sui", "slug": "sui", "rank": 29, "cmc_id": 20947},
    {"symbol": "SEI", "name": "Sei", "slug": "sei", "rank": 30, "cmc_id": 23149},
    {"symbol": "AAVE", "name": "Aave", "slug": "aave", "rank": 31, "cmc_id": 7278},
    {"symbol": "MKR", "name": "Maker", "slug": "maker", "rank": 32, "cmc_id": 1518},
    {"symbol": "RUNE", "name": "THORChain", "slug": "thorchain", "rank": 33, "cmc_id": 4157},
    {"symbol": "GRT", "name": "The Graph", "slug": "the-graph", "rank": 34, "cmc_id": 6719},
    {"symbol": "FET", "name": "Artificial Superintelligence Alliance", "slug": "fetch", "rank": 35, "cmc_id": 3773},
    {"symbol": "RNDR", "name": "Render", "slug": "render", "rank": 36, "cmc_id": 5690},
    {"symbol": "IMX", "name": "Immutable", "slug": "immutable-x", "rank": 37, "cmc_id": 10603},
    {"symbol": "PEPE", "name": "Pepe", "slug": "pepe", "rank": 38, "cmc_id": 24478},
    {"symbol": "WIF", "name": "dogwifhat", "slug": "dogwifhat", "rank": 39, "cmc_id": 28752},
    {"symbol": "FLOKI", "name": "FLOKI", "slug": "floki", "rank": 40, "cmc_id": 9258},
    {"symbol": "MATIC", "name": "Polygon", "slug": "polygon", "rank": 41, "cmc_id": 3890},
    {"symbol": "ALGO", "name": "Algorand", "slug": "algorand", "rank": 42, "cmc_id": 4030},
    {"symbol": "VET", "name": "VeChain", "slug": "vechain", "rank": 43, "cmc_id": 3077},
    {"symbol": "HBAR", "name": "Hedera", "slug": "hedera", "rank": 44, "cmc_id": 4642},
    {"symbol": "QNT", "name": "Quant", "slug": "quant", "rank": 45, "cmc_id": 3155},
    {"symbol": "STX", "name": "Stacks", "slug": "stacks", "rank": 46, "cmc_id": 4847},
    {"symbol": "LDO", "name": "Lido DAO", "slug": "lido-dao", "rank": 47, "cmc_id": 8000},
    {"symbol": "ENA", "name": "Ethena", "slug": "ethena", "rank": 48, "cmc_id": 30281},
    {"symbol": "JUP", "name": "Jupiter", "slug": "jupiter", "rank": 49, "cmc_id": 29210},
    {"symbol": "PYTH", "name": "Pyth Network", "slug": "pyth-network", "rank": 50, "cmc_id": 28177},
]

# Volume Shock demo: latest snapshot volume >= 3x baseline
VOLUME_SHOCK_MULTIPLIERS: dict[str, float] = {
    "DOGE": 5.2,
    "SHIB": 4.6,
    "PEPE": 6.1,
    "WIF": 5.8,
    "FLOKI": 4.2,
    "TRX": 3.5,
    "AVAX": 3.2,
}

# Price Shock demo: stable baseline + spike on latest snapshot
PRICE_SHOCK_BASELINE_24H: dict[str, list[float]] = {
    "SOL": [1.2, 1.0, 1.1, 0.9, 1.3],
    "NEAR": [0.8, 1.0, 0.7, 0.9, 1.1],
    "INJ": [0.5, 0.6, 0.4, 0.7, 0.5],
    "APT": [1.0, 0.8, 1.1, 0.9, 1.0],
    "SUI": [1.5, 1.2, 1.4, 1.1, 1.3],
}

PRICE_SHOCK_LATEST_24H: dict[str, float] = {
    "SOL": 8.40,
    "NEAR": 7.50,
    "INJ": 9.20,
    "APT": 6.80,
    "SUI": 7.90,
}

# Quiet Accumulation: high volume + flat price on latest
QUIET_ACCUMULATION: dict[str, dict[str, float]] = {
    "LINK": {"volume_multiplier": 4.0, "latest_pct": 0.80},
    "TON": {"volume_multiplier": 3.5, "latest_pct": 1.10},
    "ARB": {"volume_multiplier": 3.8, "latest_pct": -0.60},
    "OP": {"volume_multiplier": 3.2, "latest_pct": 1.40},
    "LDO": {"volume_multiplier": 4.5, "latest_pct": 0.30},
}

# Approximate anchor prices for seed snapshots (USD)
ANCHOR_PRICES: dict[str, str] = {
    "BTC": "104250.00",
    "ETH": "3785.50",
    "USDT": "1.0001",
    "XRP": "0.5820",
    "BNB": "685.20",
    "SOL": "178.40",
    "USDC": "0.9998",
    "DOGE": "0.1425",
    "ADA": "0.4850",
    "TRX": "0.2450",
    "LINK": "15.80",
    "AVAX": "38.25",
    "XLM": "0.1120",
    "TON": "6.45",
    "SHIB": "0.00002450",
    "DOT": "7.85",
    "BCH": "485.00",
    "LTC": "98.50",
    "UNI": "11.20",
    "NEAR": "5.10",
    "APT": "0.6685",
    "ICP": "12.80",
    "ETC": "28.50",
    "FIL": "6.20",
    "ARB": "1.15",
    "OP": "2.45",
    "INJ": "28.90",
    "ATOM": "9.80",
    "SUI": "3.85",
    "SEI": "0.5200",
    "AAVE": "285.00",
    "MKR": "1850.00",
    "RUNE": "5.40",
    "GRT": "0.2150",
    "FET": "1.85",
    "RNDR": "8.90",
    "IMX": "1.65",
    "PEPE": "0.00001280",
    "WIF": "2.85",
    "FLOKI": "0.00018500",
    "MATIC": "0.5200",
    "ALGO": "0.2850",
    "VET": "0.0420",
    "HBAR": "0.2850",
    "QNT": "98.00",
    "STX": "2.15",
    "LDO": "2.05",
    "ENA": "0.9200",
    "JUP": "1.12",
    "PYTH": "0.3850",
}
